### ISSUE TITLE
Improve logging and implement consistent error message numbering

### ISSUE THREAD

**Issue by ainsey11** [pier-oliviert/phonebook#6]
Raising as a TODO for myself

I would like to implement a standardised logging convention, following from the one @pier-oliviert has already implemented

I propose the convention of:

`PB-<provider>-#number`

For example, an error in the azure provider would be: `PB-AZ-#0001 <message>` 

This can then map back to a corresponding section within the documentation, and makes it easier to add new codes in future without worrying about overlaps

**Comment by pier-oliviert** [comment]
I believe this should be closed with https://github.com/pier-oliviert/phonebook/pull/7 being merged?

**Comment by ainsey11** [comment]
Yep! This can now be closed,

Thanks! 👌
